export const config: any = {

    connect: {
        "url": "http://localhost:",
        "port": "4024"
    },

  accessform: {
    "ACCESS_REQUEST_FORM": "Access Request Form",
    "CATEGORY": "Category",
    "EMPLOYEE": "Employee",
    "CLIENT": "Client",
    "CONSULTANTS": "Consultants",
    "CONTRACTORS": "Contractors",
    "OUTSOURCED": "Outsourced",
    "THIRD_PARTY_VENDORS": "Third Party Vendors",
    "ACCESSTYPE": "Access Type",
    "NEW_ACCESS": "New Access",
    "LOST": "Lost",
    "LOCATION_CHANGE": "Location Change",
    "DAMAGE": "Damage"
  },

  damage: {
    "DAMAGE_FORM": "Damaged Card Form",
    "EMP_ID": "Employee Id",
    "EMP_TYPE": "Employee Type",
    "PERMANENT": "Permanent",
    "TEMPORARY": "Temporary",
    "NAME": "Employee Name",
    "DOJ": "Date Of Joining",
    "DESIGNATION": "Designation",
    "PROJECT": "Project/Function",
    "OU": "OU/Designation",
    "COMMENTS_HEADING": "**First Submit Your damaged Access Card then  request for a new card And you Will Have A New Card In Two Days",
    "SUBMIT_DATE": "Enter The Date Of Card submitted",
    "SUBMIT": "Submit Your Request",
    "BACK": "Go Back"
  },

  locationchange: {
    "GENERAL": "General (All Fields Are Mandatory)",
    "CATEGORY": "Category",
    "ACCESS_TYPE": "Access Type",
    "LOCATION_CHANGE_FORM": "Location Change Form",
    "EMP_ID": "Employee ID",
    "EMP_TYPE": "Employee Type",
    "PERMANANT": "Permanent",
    "TEMPORARY": "Temporary",
    "NAME": "Name",
    "DOJ": "Date of Joining",
    "DESIGNATION": "Designation",
    "PROJECT": "Project/Function",
    "OU": "OU/Department",
    "STATUS": "Status",
    "DOE": "Date of Expiry of Temporary Card",
    "PROJECT_TRANSFER": "Project Transfer (In Case of Transfer)",
    "EXISTING_LOCATION": "Existing Location",
    "NEW_LOCATION": "New Location",
    "SIGNATURES": "Signatures",
    "APPLICANTS_SIGNATURES": "Applicants Signature",
    "DATE": "Date",
    "SUBMIT": "Submit Your Request",
    "BACK": "Go Back"
  },

  lost: {
    "EMP_ID": "Employee Id",
    "EMP_TYPE": "Employee Type",
    "PERMANANT": "Permanent",
    "TEMPORARY": "Temporary",
    "NAME": "Name",
    "DOJ": "Date of Joining",
    "DESIGNATION": "Designation",
    "PROJECT": "Project/Function",
    "OU": "OU/Department",
    "DATEOFLOSS": "Date of Loss",
    "SUBMIT": "Submit Your Request",
    "BACK": "Go Back"
  },

  thirdparty: {
    "GENERAL": "General (All Fields Are Mandatory)",
    "CATEGORY": "Category",
    "ACCESS_TYPE": "Access Type",
    "THIRD_PARTY": "Third Party Form",
    "EMP_ID": "Employee Id",
    "NAME": "Employee Name",
    "VISITOR_NAME": "Visitor Name",
    "DURATION": "Duration",
    "VISITING_PURPOSE": "Visiting Purpose",
    "SIGNATURES": "Signatures",
    "APPLICANTS_SIGNATURE": "Applicants Signature",
    "DATE": "Date",
    "SUBMIT": "Submit Your Request",
    "BACK": "Go Back"
  },

  newaccess: {
    "IR": "IR 71 Form",
    "EMPP_ID": "Employee Id",
    "EMPP_TYPE": "Employee Type",
    "TEMP": "Temporary",
    "PERM": "Permanent",
    "NAME": "NAME",
    "DATE_JOINING": "Date Of Joining",
    "DESG": "Designation",
    "PROJ": "Project/Function",
    "OU": "OU/Department",
    "STATUS": "Status",
    "DATE_EXP_CARD": "Date of Expiry of Temporary Card",
    "PRO_TRANS": "Project Transfer (In Case of Transfer)",
    "EXIST_PROJ": "Existing Project Name",
    "NEW_PROJ": "New Project Name",
    "SIGN": "Signatures",
    "ENTER_CREDENTIALS": "Enter Your Credentials",
    "APPLICANT_SIGN": "Applicants Signature",
    "DATE": "Date",
    "SUBMIT": "Submit Your Request",
    "BACK": "Go Back",
    "MSG": "Message",
    "FORWARD_MSG": "Your request has been forwarded to Supervisor",
    "BACK_MSG": "Do you really want to go back?"
  },

  employeedash: {
    "CENTRALIZED_ACCESS_CONTROL": "Centralized Access Control",
    "DASHBOARD": "Dashboard",
    "NEW_REQUEST": "New Request",
    "HISTORY": "History",
    "MY_DASHBOARD": "My Dashboard",
    "YOUR_DETAILS": "Your Details",
    "SUPERVISOR_NAME": "Chander Sehgal",
    "SUP_NAME": "Supervisor Name",
    "LOCATION": "LOCATION",
    "LOC": "Location",
    "DEPT": "SSB-CSDM-RP",
    "OU": "OU",
    "UPDATES": "Updated yesterday at 11:59 PM",
    "COPYRIGHT": "Iniitiian.com 2017"
  },

  supervisorform: {
    "IR_HEADING": "IR 71 Access Request Form",
    "VERSION": "Ver 1.0",
    "GENERAL": "General (All Fields Are Mandatory)",
    "CATEGORY": "Category",
    "ACCESS_TYPE": "Access Type",
    "IR": "IR 71 Form",
    "EMPP_ID": "Employee ID",
    "EMPP_TYPE": "Employee Type",
    "NAME": "NAME",
    "DATE_JOINING": "Date Of Joining",
    "DESG": "Designation",
    "PROJ": "Project/Function",
    "OU": "OU/Department",
    "STATUS": "Status",
    "DATE_EXP_CARD": "Date of Expiry of Temporary Card",
    "PRO_TRANS": "Project Transfer (In Case of Transfer",
    "EXIST_PROJ": "Existing Project Name",
    "NEW_PROJ": "New Project Name",
    "SIGN": "Signatures",
    "APPLICANT_SIGN": "Applicants Signature",
    "DATE": "Date",
    "PHYSICAL_ACCESS": "Physical Access Requirements (To be filled by DH/PH/PM)",
    "ZONES": "Zones",
    "PUBLIC": "Public",
    "INTERNAL": "Internal",
    "RESTRICTED": "Restricted",
    "DETAILS": "Details",
    "TEMP": "Temporary",
    "PERM": "Permanent",
    "Auth_SIGN": "Authorization Signatures (As Applicable)",
    "HRO": "HRO",
    "CSO": "CSO",
    "DH": "DH/PH/PM",
    "CISO": "CISO",
    "DATE_FORMAT": "DATE: __/__/____",
    "ACCEPT": "Accept",
    "SENDBACK": "Send Back",
    "MSG": "Message",
    "FORWARD_MSG": "Your request has been forwarded successfully",
    "BACK_MSG": "Do you really want to send it back to Employee?",
    "YES": "Yes",
    "NO": "No"
  },

  supervisordash: {
    "CENTRALIZED_ACCESS_CONTROL": "Centralized Access Control",
    "DASHBOARD": "Dashboard",
    "NEW_REQUEST": "New Request",
    "ACCESS_REQUESTS": "Access Requests",
    "MESSAGES": "Messages",
    "NEW_MESSAGES": "New Messages",
    "VIEW_ALL_MESSAGES": "View all Messages",
    "VIEW_ALL_ALERTS": "View all alerts",
    "BACK_TO_INIITIAN_PORTAL": "Back to Iniitian portal",
    "MY_DASHBOARD": "My Dashboard",
    "YOUR_REQUEST_IS_APPROVED_PENDING": "Your request is Approved/Pending",
    "YOUR_DETAILS": "Your Details",
    "NEW_ACCESS_REQUESTS": "New Access Requests",
    "LOCATION_CHANGE_REQUESTS": "Location Change Requests",
    "LOST_CARD_REQUESTS": "Lost Card Requests",
    "DAMAGE_REQUESTS": "Damage Requests",
    "S_NO": "S.No.",
    "EMPLOYEE_ID": "Employee Id",
    "EMPLOYEE_NAME": "Employee Name",
    "COPYRIGHT": "Copyright &copy; Iniitian.com 2017"
  },

  hrform: {
    "IMGSRC": "http://www.niit-tech.com/niit_technologies_logo.jpg",
    "IRHEADING": "IR 71 Access Request Form",
    "VERSION": "Ver 1.0",
    "GUIDELINES": "Click Here To See Guidelines",
    "GENERAL": "General (All Fields Are Mandatory)",
    "CATEGORY": "Category",
    "ACCESS": "Access Type",
    "IR_FORM": "IR 71 Form",
    "EMP_ID": "Employee ID",
    "EMP_TYPE": "Employee Type",
    "NAME": "Name",
    "DOJ": "Date of Joining",
    "DESIGNATION": "Designation",
    "PROJECT": "Project/Function",
    "OU": "OU/Department",
    "STATUS": "Status",
    "PERMANENT": "Permanent",
    "TEMPORARY": "Temporary",
    "DOE_TEMP": "Date of Expiry of Temporary Card",
    "PROJECT_TRANSFER": "Project Transfer (In Case of Transfer)",
    "EXISTING_PROJECT": "Existing Project Name",
    "NEW_PROJECT": "New Project Name",
    "SIGNATURES": "Signatures",
    "APPLICANTS_SIGN": "Applicants Signature",
    "DATE": "Date",
    "PHY_ACCESS": "Physical Access Requirements (To be filled by DH/PH/PM)",
    "ZONES": "Zones",
    "PUBLIC": "Public",
    "INTERNAL": "Internal",
    "RESTRICTED": "Restricted",
    "DETAILS": "Details",
    "AUTHORIZE_SIGN": "Authorization Signatures (As Applicable)",
    "HRO": "HRO",
    "CSO": "CSO",
    "DH_PH_PM": "DH/PH/PM",
    "CISO": "CISO",
    "ACCEPT": "Accept",
    "SEND_BACK": "Send Back",
    "MESSAGE": "Message",
    "SUCCESS_MSG": "Your request has been forwarded successfully",
    "BACK_MSG": "Do you really want to send it back to Supervisor",
    "YES": "Yes",
    "NO": "No"
  },

  hrdashboard: {
    "CENTRALIZED_ACCESS_CONTROL": "Centralized Access Control",
    "DASHBOARD": "Dashboard",
    "NEW_REQUEST": "New Request",
    "ACCESS_REQUESTS": "Access Requests",
    "MESSAGES": "Messages",
    "NEW_MESSAGES": "New Messages",
    "VIEW_ALL_MESSAGES": "View all Messages",
    "VIEW_ALL_ALERTS": "View all alerts",
    "BACK_TO_INIITIAN_PORTAL": "Back to Iniitian portal",
    "MY_DASHBOARD": "My Dashboard",
    "YOUR_REQUEST_IS_APPROVED_PENDING": "Your request is Approved/Pending",
    "YOUR_DETAILS": "Your Details",
    "NEW_ACCESS_REQUESTS": "New Access Requests",
    "LOCATION_CHANGE_REQUESTS": "Location Change Requests",
    "LOST_CARD_REQUESTS": "Lost Card Requests",
    "DAMAGE_REQUESTS": "Damage Requests",
    "S_NO": "S.No.",
    "EMPLOYEE_ID": "Employee Id",
    "EMPLOYEE_NAME": "Employee Name",
    "COPYRIGHT": "Iniitian.com 2017"
  },

  csoform: {
    "IMG_SRC": "http://www.niit-tech.com/niit_technologies_logo.jpg",
    "IR_HEADING": "IR 71 Access Request Form",
    "VERSION": "Ver 1.0",
    "GUIDELINE_MODAL": "Click Here To See Guidelines",
    "GENERAL": "General (All Fields Are Mandatory)",
    "CATEGORY": "Category",
    "ACCESS_TYPE": "Access Type",
    "IR_FORM": "IR 71 Form",
    "EMP_ID": "Employee ID",
    "EMP_TYPE": "Employee Type",
    "NAME": "Name",
    "DOJ": "Date of Joining",
    "DESIGNATION": "Designation",
    "PROJECT": "Project/Function",
    "OU": "OU/Department",
    "STATUS": "Status",
    "PERMANENT": "Permanent",
    "TEMPERORY": "Temporary",
    "DOE_TEMP": "Date of Expiry of Temporary Card",
    "PROJECT_TRANSFER": "Project Transfer (In Case of Transfer)",
    "EXISTING_PROJECT": "Existing Project Name",
    "NEW_PROJECT": "New Project Name",
    "SIGNATURES": "Signatures",
    "APPLICANTS_SIGNATURES": "Applicants Signature",
    "DATE": "Date",
    "PHYSICAL_ACCESS": "Physical Access Requirements (To be filled by DH/PH/PM)",
    "ZONES": "Zones",
    "PUBLIC": "Public",
    "INTERNAL": "Internal",
    "RESTRICTED": "Restricted",
    "DETAILS": "Details",
    "ACCESS_CARD_DETAIL": "Access Card Details (To be filled by CSO)",
    "ACCESS_CARD_NUMBER": "Access Card Number",
    "ISSUED_BY": "Issued By",
    "AUTHORIZE_SIGN": "Authorization Signatures (As Applicable)",
    "HRO": "HRO",
    "CSO": "CSO",
    "DH_PH_PM": "DH/PH/PM",
    "CISO": "CISO",
    "DATE_FORMAT": "Date: __/ __/____",
    "ACCEPT": "Accept",
    "SEND_BACK": "Send Back",
    "SUCCESSFUL_ALLOT": "Access card alloted successfully",
    "BACK_MSG": "Do you really want to send it back to Hr?",
    "MESSAGE": "Message",
    "YES": "Yes",
    "NO": "No"
  },

  csodash: {
    "CAC": "Centralized Access Control",
    "DASHBOARD_LABEL": "Dashboard",
    "NEW_REQ": "New Request",
    "ACCESS_REQ": "Access Requests",
    "MESSAGES": "Messages",
    "MESSAGE_NUMBER": "12",
    "NEW_MESSAGE_LABEL": "New Messages:",
    "SENDER_NAME": "Tanupreet",
    "RECIEVING_TIME": "11:21 AM",
    "PING": "Hey Prakhar",
    "SENDER_NAME_SECOND": "Shivam",
    "MESSAGE": "Hi!!!",
    "BACK": "Back To Iniitian Portal",
    "MYDASHBOARD": "My Dashboard",
    "STATUS": "Your Request is Approved / Pending",
    "DETAILS": "Your Details",
    "OU_LABEL": "OU",
    "LOCATION_LABEL": "Location",
    "NEW_ACCESS": "New Access Requests",
    "LOCATION_CHANGE": "Location Change Requests",
    "LOST_CARD": "Lost Card Requests",
    "DAMAGE_CARD": "Damage Requests",
    "S_NO": "S. No.",
    "EMP_ID": "Employee Id",
    "EMP_NAME": "Employee name",
    "COPYRIGHT": "Copyright &copy; Iniitian.com 2017",
    "VIEW_ACTIVITY": "View all activity...",

  }
};
